trigger: none # ningun gatillo

pool:
  name: local # la original si fuera la maquina virtual es vmImage: ubuntu-latest, al utilizar un agente auto-hospedado se usa name: local 

steps:
- task: TerraformTaskV4@4 # tarea inicio
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Templates'
    backendServiceArm: 'Azure for Students(23dd767a-27e3-434a-883f-5cef612f88fe)'
    backendAzureRmResourceGroupName: 'Grupojalg'
    backendAzureRmStorageAccountName: 'almacenamientojalg'
    backendAzureRmContainerName: 'contenedorjose'
    backendAzureRmKey: 'terraform.tfstate'
  displayName: 'Terraform Init'

- task: TerraformTaskV4@4 # indica comando tarea en este caso comando destroy
  inputs:
    provider: 'azurerm'
    command: 'destroy' # mediante este comando se inicia la destruccion de la pipeline
    workingDirectory: '$(System.DefaultWorkingDirectory)/Templates'
    commandOptions: '--auto-approve' # automatica sin preguntar si se quiere realizar
    environmentServiceNameAzureRM: 'Azure for Students(23dd767a-27e3-434a-883f-5cef612f88fe)'
  displayName: 'Terraform Destroy' # mostrara esto en pantalla
